// Code generated by simpleapi. DO NOT EDIT.
package role_api

import (
	"google.golang.org/protobuf/proto"
	"simple/lib/simpleapi"
	"simple/lib/simplenet"
)

func (s *RoleApi) ServiceID() byte {
	return 1
}
func (s *RoleApi) NewRequest(id byte) simpleapi.Message {
	switch id {
	case 1:
		return &LoginReq{}
	}
	return nil
}
func (s *RoleApi) NewResponse(id byte) simpleapi.Message {
	switch id {
	case 1:
		return &LoginRes{}
	}
	return nil
}
func (s *RoleApi) HandleRequest(session *simplenet.Session, req simpleapi.Message) {
	switch req.MessageID() {
	case 1:
		session.Send(s.Login(session, req.(*LoginReq)))
	default:
		panic("Unhandled Message Type")
	}
}
func (m *LoginReq) ServiceID() byte {
	return 1
}
func (m *LoginReq) MessageID() byte {
	return 1
}
func (m *LoginReq) Identity() string {
	return "RoleApi.LoginReq"
}
func (m *LoginReq) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}
func (m *LoginReq) Unmarshal(p []byte) error {
	return proto.Unmarshal(p, m)
}
func (m *LoginRes) ServiceID() byte {
	return 1
}
func (m *LoginRes) MessageID() byte {
	return 1
}
func (m *LoginRes) Identity() string {
	return "RoleApi.LoginRes"
}
func (m *LoginRes) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}
func (m *LoginRes) Unmarshal(p []byte) error {
	return proto.Unmarshal(p, m)
}
