// Code generated by simpleapi. DO NOT EDIT.
package role_api

import (
	"simple/lib/mynet"
	"simple/lib/simpleapi"
)

func (api *RoleApi) ServiceID() byte {
	return 1
}
func (api *RoleApi) NewRequest(id byte) simpleapi.Message {
	switch id {
	case 1:
		return &LoginReq{}
	}
	return nil
}
func (api *RoleApi) NewResponse(id byte) simpleapi.Message {
	switch id {
	case 1:
		return &LoginRes{}
	}
	return nil
}
func (s *RoleApi) HandleRequest(session *mynet.Session, req simpleapi.Message) {
	switch req.MessageID() {
	case 1:
		session.Send(s.Add(session, req.(*LoginReq)))
	default:
		panic("Unhandled Message Type")
	}
}
func (msg *LoginReq) ServiceID() byte {
	return 1
}
func (msg *LoginReq) MessageID() byte {
	return 1
}
func (msg *LoginReq) Identity() string {
	return "RoleApi.LoginReq"
}
func (msg *LoginRes) ServiceID() byte {
	return 1
}
func (msg *LoginRes) MessageID() byte {
	return 1
}
func (msg *LoginRes) Identity() string {
	return "RoleApi.LoginRes"
}
